name: SulfurFun
description: $description
version: '0.0.0-Experimental'

main: de.jgaertig.sulfurFun.SulfurFun
api-version: '26.1'

authors: [ j-gaertig ]
website: https://github.com/j-gaertig/SulfurPlay

commands:
  newgame:
    permission: op
    permission-message: "Warning: This Command is for Server OPs only!"
    usage: "/newgame <type_of_minigame> <name_of_your_arena>"